### ISSUE TITLE
Root window blurs on Xorg

### ISSUE THREAD

**Issue by eMorph** [ckissane/blur-me#12] opened 2021-05-08 18:25 UTC
When application blur is enabled, the root window also blurs.
![Screenshot from 2021-05-08 14-24-01](https://user-images.githubusercontent.com/50468391/117549585-3b3d4f00-b009-11eb-9488-3687900dd397.png)

**Comment by ckissane** [comment] 2021-05-08 21:08
@eMorph I have not been able to reproduce this, could you give me your gnome version etcetera?

**Comment by eMorph** [comment] 2021-05-09 13:58
40.0

**Comment by eMorph** [comment] 2021-05-09 14:33
Looking at the screenshot now, I just noticed the way that shadows remain unblurred and I think that's really cool.

**Comment by eMorph** [comment] 2021-05-09 14:41
Display drivers: NVIDIA-SMI 465.27, Mesa 21.0.3

**Comment by ckissane** [comment] 2021-05-10 03:36
Ah I was about to ask what other extensions you have and I think it is because of the desktop icons extension.

**Comment by ckissane** [comment] 2021-05-10 03:37
@eMorph This will be fixed when the ability to disable blur for certain window classes is added. When it is you can just disable the blur on the desktop icons window.

**Comment by ckissane** [comment] 2021-05-11 17:18
Yeah your right, I made it do process name now

**Closed** 2021-05-12 02:49 UTC
